"use client";

import { ChangeEvent, PointerEvent, useMemo, useState } from "react";

type Path = "narrative" | "atmosphere";
type Story = {title:string;genre:string;theme:string;logline:string;characters:Array<{name:string;identity:string;desire:string;need:string;flaw:string;arc:string}>;world:string;openingHook:string;synopsis:string;beats:Array<{name:string;content:string;emotion:string}>;climax:string;ending:string;continuityBible:string};
type Shot={id:string;duration:string;beat:string;shotSize:string;visual:string;lighting:string;dialogue:string;sound:string;camera:string;purpose:string;continuity:string};
type PromptItem={id:string;imagePrompt:string;videoPrompt:string;negativePrompt:string};

export default function Home(){
  const [path,setPath]=useState<Path>("narrative"); const [idea,setIdea]=useState(""); const [minutes,setMinutes]=useState(1); const [seconds,setSeconds]=useState(0);
  const [mediaName,setMediaName]=useState(""); const [frames,setFrames]=useState<string[]>([]); const [sourceType,setSourceType]=useState<"image"|"video">("image"); const [analysis,setAnalysis]=useState(""); const [analysisOK,setAnalysisOK]=useState(false);
  const [story,setStory]=useState<Story|null>(null); const [storyText,setStoryText]=useState(""); const [storyOK,setStoryOK]=useState(false); const [shots,setShots]=useState<Shot[]>([]); const [shotsOK,setShotsOK]=useState(false); const [prompts,setPrompts]=useState<PromptItem[]>([]);
  const [selected,setSelected]=useState("01"); const [loading,setLoading]=useState<string|null>(null); const [status,setStatus]=useState("请选择一条工作流"); const [offset,setOffset]=useState({x:35,y:35}); const [drag,setDrag]=useState<{x:number;y:number;ox:number;oy:number}|null>(null);
  const targetSeconds=useMemo(()=>Math.max(1,minutes*60+seconds),[minutes,seconds]); const actualSeconds=shots.reduce((sum,s)=>sum+(Number.parseInt(s.duration)||0),0); const currentShot=shots.find(s=>s.id===selected); const currentPrompt=prompts.find(p=>p.id===selected);
  function reset(next:Path){setPath(next);setAnalysis("");setAnalysisOK(false);setStory(null);setStoryOK(false);setShots([]);setShotsOK(false);setPrompts([]);setStatus(next==="narrative"?"剧情工作流已启用，氛围参考路径已停用":"氛围工作流已启用，剧本直写路径已停用")}
  async function api(url:string,body:unknown){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"请求失败");return d}
  async function handleMedia(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setMediaName(file.name);setAnalysis("");setAnalysisOK(false);try{if(file.type.startsWith("image/")){setSourceType("image");setFrames([await readFile(file)])}else if(file.type.startsWith("video/")){setSourceType("video");setStatus("正在从视频中抽取代表画面…");setFrames(await extractVideoFrames(file,4));setStatus("视频抽帧完成，可以开始拆解")}else setStatus("请上传图片或视频")}catch{setStatus("素材读取失败，请更换文件")}}
  async function analyze(){if(!frames.length)return setStatus("请先上传图片或视频");setLoading("analysis");setStatus(sourceType==="video"?"豆包正在快速拆解视频镜头、运镜与风格…":"豆包正在快速拆解图片风格氛围…");try{const d=await api("/api/vision",{images:frames,sourceType,quality:"lite"});setAnalysis(d.profile);setAnalysisOK(false);setStatus("拆解完成，请确认后生成氛围脚本")}catch(e){setStatus(e instanceof Error?e.message:"拆解失败")}finally{setLoading(null)}}
  async function makeStory(){if(!idea.trim())return setStatus("请先填写故事大纲或表达主题");if(path==="atmosphere"&&!analysisOK)return setStatus("请先上传并确认参考素材拆解");setLoading("story");setStatus(path==="narrative"?"职业编剧正在创作完整剧情…":"正在结合参考风格与大纲创作氛围脚本…");try{const d=await api("/api/generate",{phase:"story",mode:path,idea,targetSeconds,referenceAnalysis:path==="atmosphere"?analysis:"无"});setStory(d.story);setStoryText(d.story.synopsis);setStoryOK(false);setShots([]);setPrompts([]);setStatus("脚本已生成，请编辑并确认")}catch(e){setStatus(e instanceof Error?e.message:"生成失败")}finally{setLoading(null)}}
  async function makeShots(){if(!story)return;setLoading("shots");setStatus(`正在生成总时长严格为 ${formatTime(targetSeconds)} 的分镜…`);try{const d=await api("/api/generate",{phase:"shots",mode:path,targetSeconds,story:{...story,synopsis:storyText},referenceAnalysis:analysis});setShots(d.storyboard.shots);setSelected(d.storyboard.shots[0]?.id||"01");setShotsOK(false);setPrompts([]);setStatus(`分镜完成：目标 ${formatTime(targetSeconds)}，实际 ${formatTime(d.storyboard.actualSeconds)}`)}catch(e){setStatus(e instanceof Error?e.message:"生成失败")}finally{setLoading(null)}}
  async function makePrompts(){setLoading("prompts");setStatus("正在生成逐镜中文提示词和AI连续性约束…");try{const d=await api("/api/generate",{phase:"prompts",story:{...story,synopsis:storyText},shots,referenceAnalysis:analysis});setPrompts(d.promptSet.prompts);setStatus("全部提示词已生成")}catch(e){setStatus(e instanceof Error?e.message:"生成失败")}finally{setLoading(null)}}
  function down(e:PointerEvent<HTMLDivElement>){if((e.target as HTMLElement).closest(".node,button,input,textarea,select,label"))return;setDrag({x:e.clientX,y:e.clientY,ox:offset.x,oy:offset.y});e.currentTarget.setPointerCapture(e.pointerId)} function move(e:PointerEvent<HTMLDivElement>){if(drag)setOffset({x:drag.ox+e.clientX-drag.x,y:drag.oy+e.clientY-drag.y})}
  return <main className="canvas-app"><header className="canvas-top"><div className="logo"><b>幕</b><span><strong>幕间</strong><small>AI 剧本与分镜工作台</small></span></div><div className="stagebar"><em className="active">1 选择路径</em><i/><em className={story?"done":""}>2 确认脚本</em><i/><em className={storyOK?"done":""}>3 确认分镜</em><i/><em className={shotsOK?"active":""}>4 生成提示词</em></div><button onClick={()=>setOffset({x:35,y:35})}>回到起点</button></header>
  <div className="infinite-canvas" onPointerDown={down} onPointerMove={move} onPointerUp={()=>setDrag(null)}><div className="canvas-world wide split-world" style={{transform:`translate(${offset.x}px,${offset.y}px)`}}><svg className="wires" width="3700" height="1500"><path className={path==="narrative"?"active-wire":"muted-wire"} d="M430 520 C500 520 500 250 560 250"/><path className={path==="atmosphere"?"active-wire":"muted-wire"} d="M430 520 C500 520 500 850 560 850"/><path className={path==="narrative"?"active-wire":"muted-wire"} d="M1030 250 C1100 250 1100 250 1160 250"/><path className={path==="atmosphere"?"active-wire":"muted-wire"} d="M1040 850 C1100 850 1100 850 1160 850"/><path className={path==="narrative"?"active-wire":"muted-wire"} d="M1630 250 C1700 250 1700 250 1760 250"/><path className={path==="atmosphere"?"active-wire":"muted-wire"} d="M1630 850 C1700 850 1700 850 1760 850"/><path className={path==="narrative"?"active-wire":"muted-wire"} d="M2410 250 C2480 250 2480 250 2540 250"/><path className={path==="atmosphere"?"active-wire":"muted-wire"} d="M2410 850 C2480 850 2480 850 2540 850"/></svg><div className={`branch-label branch-narrative ${path==="narrative"?"selected-branch":""}`}>剧情向 · 故事创作线</div><div className={`branch-label branch-atmosphere ${path==="atmosphere"?"selected-branch":""}`}>氛围向 · 素材驱动线</div>
  <section className="node brief-node" style={{left:0,top:35}}><NodeHead n="01" title="选择工作流" state="必选"/><div className="route-cards"><button className={path==="narrative"?"active":"muted"} onClick={()=>reset("narrative")}><b>剧情向</b><span>专业剧本撰写</span><small>人物、冲突、转折、高潮</small></button><button className={path==="atmosphere"?"active":"muted"} onClick={()=>reset("atmosphere")}><b>氛围向</b><span>参考素材拆解</span><small>视频镜头 / 图片风格氛围</small></button></div><label>自定义片长<div className="duration-input"><input type="number" min="0" max="60" value={minutes} onChange={e=>setMinutes(Math.max(0,+e.target.value))}/><span>分</span><input type="number" min="0" max="59" value={seconds} onChange={e=>setSeconds(Math.min(59,Math.max(0,+e.target.value)))}/><span>秒</span></div><small className="duration-total">目标总时长：{formatTime(targetSeconds)}</small></label><label>{path==="narrative"?"故事创意（必填）":"内容大纲与表达主题（必填）"}<textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder={path==="narrative"?"写下人物、困境、目标或故事构想…":"写下视频要表达的主题、情绪变化和核心内容…"}/></label>{path==="narrative"&&<button className="primary full" onClick={makeStory} disabled={!idea.trim()||!!loading}>{loading==="story"?"编剧创作中…":idea.trim()?"生成专业剧本 →":"请先填写创意点"}</button>}</section>
  <section className={`node analysis-node ${path==="narrative"?"disabled-node":""}`} style={{left:560,top:35}}><NodeHead n="02A" title="参考素材拆解" state={path==="narrative"?"已停用":analysisOK?"已确认":analysis?"待确认":"等待"}/>{path==="narrative"?<Empty text="当前选择剧情向工作流，此路径已停用"/>:<>{!idea.trim()&&<div className="gate-note">请先在“内容大纲与表达主题”填写创意点，才能上传和拆解素材。</div>}<label className="media-upload"><input type="file" accept="image/*,video/*" onChange={handleMedia} disabled={!idea.trim()}/><b>＋ 上传视频或图片</b><small>{mediaName||"快速模式：视频自动抽取4个代表画面"}</small></label>{frames.length>0&&<div className="frame-strip">{frames.map((f,i)=><img src={f} alt={`参考画面${i+1}`} key={i}/>)}</div>}<button className="primary full" onClick={analyze} disabled={!idea.trim()||!frames.length||!!loading}>{loading==="analysis"?"拆解中…":!idea.trim()?"请先填写大纲创意点":sourceType==="video"?"拆解视频镜头与风格":"拆解图片风格氛围"}</button>{analysis&&<textarea className="analysis-editor" value={analysis} onChange={e=>{setAnalysis(e.target.value);setAnalysisOK(false)}}/>}{analysis&&<div className="node-actions"><button className="primary" onClick={()=>{setAnalysisOK(true);setStatus("素材拆解已确认，可以结合大纲生成脚本")}}>确认拆解 ✓</button></div>}</>}</section>
  <section className="node story-node" style={{left:1160,top:35}}><NodeHead n="02B" title={path==="narrative"?"专业剧本":"氛围脚本"} state={storyOK?"已确认":story?"待确认":"等待"}/>{path==="atmosphere"&&analysisOK&&!story?<Empty text="根据已确认的拆解内容和大纲生成脚本"><button className="primary" onClick={makeStory}>{loading==="story"?"生成中…":"生成氛围脚本 →"}</button></Empty>:story?<><h2>{story.title}</h2><p className="logline">{story.logline}</p><textarea className="story-editor" value={storyText} onChange={e=>{setStoryText(e.target.value);setStoryOK(false)}}/><div className="beats">{story.beats.map((b,i)=><div key={i}><b>{i+1}</b><span><strong>{b.name}</strong><small>{b.content}</small></span></div>)}</div><div className="node-actions"><button onClick={makeStory}>重新生成</button><button className="primary" onClick={()=>{setStoryOK(true);setStatus("脚本已确认，可以生成分镜")}}>确认脚本 ✓</button></div></>:<Empty text={path==="narrative"?"填写创意后生成专业剧情脚本":"请先完成并确认参考素材拆解"}/>}</section>
  <section className="node shots-node" style={{left:1760,top:35}}><NodeHead n="03" title="导演分镜台" state={shotsOK?"已确认":shots.length?"待确认":"等待"}/>{storyOK&&!shots.length?<Empty text={`将镜头总时长严格匹配 ${formatTime(targetSeconds)}`}><button className="primary" onClick={makeShots}>{loading==="shots"?"拆解中…":"生成分镜镜头 →"}</button></Empty>:shots.length?<><div className={`duration-check ${actualSeconds===targetSeconds?"ok":"bad"}`}>目标 {formatTime(targetSeconds)}　实际 {formatTime(actualSeconds)}　{actualSeconds===targetSeconds?"✓ 时长一致":"⚠ 时长不一致"}</div><div className="shot-list">{shots.map(s=><button key={s.id} className={selected===s.id?"selected":""} onClick={()=>setSelected(s.id)}><b>{s.id}</b><span><strong>{s.shotSize} · {s.duration}</strong><small>{s.visual}</small></span></button>)}</div>{currentShot&&<div className="shot-inspect"><b>{currentShot.beat}</b><p>{currentShot.camera}</p><small>连续性：{currentShot.continuity}</small></div>}<div className="node-actions"><button onClick={makeShots}>重新拆分</button><button className="primary" disabled={actualSeconds!==targetSeconds} onClick={()=>{setShotsOK(true);setStatus("分镜与片长已确认，可以生成提示词")}}>确认分镜 ✓</button></div></>:<Empty text="请先确认脚本"/>}</section>
  <section className="node prompt-node" style={{left:2540,top:35}}><NodeHead n="04" title="画面与运动提示词" state={prompts.length?"已生成":"等待"}/>{shotsOK&&!prompts.length?<Empty text="为已确认镜头生成全中文提示词"><button className="primary" onClick={makePrompts}>{loading==="prompts"?"生成中…":"生成最终提示词 →"}</button></Empty>:currentPrompt?<><div className="prompt-tabs">镜头 {selected} · {currentShot?.duration}</div><Prompt title="分镜图提示词" text={currentPrompt.imagePrompt}/><Prompt title="视频运动提示词" text={currentPrompt.videoPrompt}/><Prompt title="AI 一致性约束" text={currentPrompt.negativePrompt}/></>:<Empty text="请先确认分镜"/>}</section>
  </div><div className="canvas-help">按住空白处拖动画布 · 两条路径互斥</div><div className="mini-status"><i/>{status}</div></div></main>
}

function NodeHead({n,title,state}:{n:string;title:string;state:string}){return <div className="node-head"><span>{n}</span><h3>{title}</h3><em>{state}</em></div>}; function Empty({text,children}:{text:string;children?:React.ReactNode}){return <div className="empty"><span>⌁</span><p>{text}</p>{children}</div>}; function Prompt({title,text}:{title:string;text:string}){return <div className="prompt-box"><div><b>{title}</b><button onClick={()=>navigator.clipboard.writeText(text)}>复制</button></div><p>{text}</p></div>}; function formatTime(total:number){return `${Math.floor(total/60)}分${total%60}秒`}
function readFile(file:File){return new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file)})}
function extractVideoFrames(file:File,count:number){return new Promise<string[]>((resolve,reject)=>{const video=document.createElement("video");const url=URL.createObjectURL(file);video.preload="metadata";video.muted=true;video.src=url;video.onloadedmetadata=async()=>{try{const canvas=document.createElement("canvas");canvas.width=Math.min(640,video.videoWidth);canvas.height=Math.round(canvas.width*video.videoHeight/video.videoWidth);const ctx=canvas.getContext("2d");if(!ctx)throw new Error();const result:string[]=[];for(let i=0;i<count;i++){video.currentTime=Math.max(0.01,video.duration*(i+.5)/count);await new Promise<void>(ok=>video.onseeked=()=>ok());ctx.drawImage(video,0,0,canvas.width,canvas.height);result.push(canvas.toDataURL("image/jpeg",.65))}URL.revokeObjectURL(url);resolve(result)}catch(e){URL.revokeObjectURL(url);reject(e)}};video.onerror=reject})}
